### ISSUE TITLE
Poor Performance

### ISSUE THREAD

**Issue by Uncle-Sagbag** [mmmaxwwwell/space-engineers-dedicated-docker-linux#13]
I am running on the `permissions` branch of the docker on Debian 10 on an AMD Ryzen system. Everything functions very well except the performance of the server. When there is more than 1 player on the server, server performance dips noticeably. In every case, connection problems occur every 15 minutes or so. This freezes the game with the warning "Connection Problem" for a few seconds.

Do other people experience such performance on the server? If not, how does your server perform much better than mine?

**Comment by mmmaxwwwell** [comment]
I've had reports of people having poor performance using different hardware. Usually its because their computer is from 2012, and has a single core clock speed equivalent to that of a literal potato.

The server I'm running runs at about native performance. 8700k, 32gb stock speed ram and a 1tb consumer grade NVME.

I can't provide support for issues like this, but feel free to bounce ideas off me or the #linux channel in the keen swh discord.
