### ISSUE TITLE
server reverted back to original save after restart

### ISSUE THREAD

**Issue by fader402** [mmmaxwwwell/space-engineers-dedicated-docker-linux#2]
Was playing on the server with 3 people total we all started getting bad lag. After several we got kicked and when we logged back in the world was reverted back to the original save. Auto save was enabled every 5 minutes.
I attached the log file.
[Space Engineers Server Log.txt](https://github.com/mmmaxwwwell/space-engineers-dedicated-docker-linux/files/5790226/Space.Engineers.Server.Log.txt)

**Comment by mmmaxwwwell** [comment]
The log file never shows a saving message. It never saved, that's why it "reverted". You can try manually saving it with a "/save" command in chat from an admin, to see what a save message looks like in the log. Check your config.

Says your processor is 32 cores, you running on old server hardware? Find another box with a higher clock speed. Disable raid if you are using it. Try and disable the remote API.
