### ISSUE TITLE
config file settings not working

### ISSUE THREAD

**Issue by Shalrath** [mmmaxwwwell/space-engineers-dedicated-docker-linux#37]
Some configuration file settings are not carrying over.  While I can see the ServerName and MaxPlayers settings being honored, almost nothing else is.  (inventory size, wolves/spiders, meteors, etc)  

Am I missing a step in the setup, or is this a known issue?

**Comment by genosh** [comment]
I will have the same problem a few days ago, but I finally found the cause:

As I uderstand, when you create a new world, the world is configured with the SpaceEngineers-Dedicated.cfg config. And once the world is created, all configuration concerning the world (no the server), is freeze. So updating your SpaceEngineers-Dedicated.cfg don't work (That happen also if you copy an existing world from other way).

That happen because when world is created, the world configuration is saved in Sandbox_config.sbc file (in the World directory). Updating this file update the world configuration.

**Comment by mmmaxwwwell** [comment]
Thanks for replying @genosh, appreciate the helpful comment!

To word it a little differently, some of those config options are duplicated in the sandbox file, and the DS ignores those duplicated ones in the dedicated server cfg. Instead, it pulls those duplicated values from the sandbox file.

So there's two files you have to look at, one of the sandbox files, and the dedicated server cfg file. 

Hope this helps

**Comment by Shalrath** [comment]
Thanks @genosh and @mmmaxwwwell, that did the trick.
