### ISSUE TITLE
Any recommendation to port this project to ARM64?

### ISSUE THREAD

**Issue by aborroy** [mmmaxwwwell/space-engineers-dedicated-docker-linux#42]
Thanks!

**Comment by mmmaxwwwell** [comment]
May I ask why you want to port it to arm?

**Comment by aborroy** [comment]
I have an Oracle Cloud instance that I want to use for this server that is based in Ampere. I guess that would be also interesting for the people using the new Apple M1 processors.

**Comment by Staijn1** [comment]
Any updates on this? I'm also using an Oracle Cloud instance

**Comment by mmmaxwwwell** [comment]
It's not possible afaik, the base game needs to be ported first. Translation or emulation to the correct architecture would perform very very poorly. I would love it if you could prove me wrong, but this isn't feasible at this time.

**Comment by BloodyIron** [comment]
There is zero realistic possibility of the game server being ported to ARM32/64. The game server would need to be significantly overhauled to change architecture, and that is definitely out of scope for this project. Plus Keen would see no realistic value in doing that for Space Engineers. If they were to do it (and they probably won't, because game servers do not have any tangible market share in ARM32/64 space), they would do it for the VRAGE3 engine, and not waste any time on Space Engineers/VRAGE2 being ported to ARM32/64.

It is absolutely, positively, a large task to port something like this to ARM64. This ticket really should just be closed as it's adding clutter.

**Comment by BloodyIron** [comment]
Sorry @aborroy , didn't want to rain on your parade, more I didn't want you to hope for something I really don't see as happening. :( Have a nice day!
