### ISSUE TITLE
Multiple issues while trying to get this to work

### ISSUE THREAD

**Issue by diniamo** [mmmaxwwwell/space-engineers-dedicated-docker-linux#53]
Stops the whole thing from working:
```
Cannot start new world - Premade world not found
```

And mods fail to download as well.

I'm not sure what I should other information I should send, any ideas?

**Comment by diniamo** [comment]
Oops, accidentally posted early

**Comment by ilmal** [comment]
You need to extract the star-system.zip file to create a World dir. 

So:

- Extract star-system.zip
- run start

As for the mods, not sure what your problem is without logs, but this is a common issue that I faced:
https://steamcommunity.com/sharedfiles/filedetails/?id=2835041807

**Comment by diniamo** [comment]
Hey, thanks for your answer.

I don't understand why I would need to unzip it myself, quoting from the README:
> Run the start script with ./start. This will initialize the ./appdata folder, **unzip an empty star system from star-system.zip** and start the server.

Even so, I did unzip it myself, and the same error comes up still. Perhaps the LoadWorld property is wrong in the config file? It's currently: Z:\appdata\space-engineers\World

As for the mods, I think I've tried that solution, but no luck. I'll do it again once we get the other issue sorted.

**Comment by ilmal** [comment]
I also had trouble with this exact issue when first booting up a server. But managed to solve it by just removing the ./appdata folder and redoing it following the documentation as precisely as possible (which probably should be rephrased to something that is easier to follow).  

As for the LoadWorld property being incorrect, you can change this and get it to work. That was my first solution (which worked), but I ended up making a mess out of the folders, basically downloading another set of ./appdata inside of my first ./appdata in order to get it to work. I eventually redid the entire thing following the instructions. 

1. run ./start (to create the ./appdata folder)
2. unzip the star-system.zip
3. run ./start again to start the server

My tip would really just be to recreate the server a couple of times and pray it will boot (a very scientific approach).

As for why the star-system is in a zip format is probably since Github doesn't like large files. Although I'm only a user of this repo, so I guess the owner is the only one who really knows. But yes, unzipping is an inconvenience.

**Comment by diniamo** [comment]
As I said, the unzipping is done automatically by the script, so why would I have to do it?
I deleted the appdata folder, ran start once, then again, and it worked, but when I stopped it and tried adding a mod, it broke. (Coming back with the error in my original message) Now I don't know if it was because of the mod or something else, so I tried deleting appdata again, but this time it doesn't work, saying:
```
SpaceEngineers-Dedicated.cfg file does not exist, exiting.
Sandbox.sbc file does not exist, exiting.
```

**Comment by ilmal** [comment]
I haven't looked into the code that much (I'm just a user) but that error comes from the entrypoint.bash file

```
# #check if /appdata/space-engineers/config/World is a folder
if [ ! -d "/appdata/space-engineers/World" ]; then
  echo "World folder does not exist, exiting"
  exit 129
fi

# #check if /appdata/space-engineers/config/World/Sandbox.sbc exists and is a file
if [ ! -f "/appdata/space-engineers/World/Sandbox.sbc" ]; then
  echo "Sandbox.sbc file does not exist, exiting."
  exit 130
fi
```
It seems you have some issues with your directory structure (where the files are placed).

I can send you how my files are structured later today (if i remember), hopefully that might help!

**Comment by mmmaxwwwell** [comment]
i pushed a commit to the v2 branch that should address the mod loading issue, closing due to age. If you still have an issue please re-open this issue or open a new one.
