### ISSUE TITLE
Server does not seem to save the world

### ISSUE THREAD

**Issue by Allesstein** [mmmaxwwwell/space-engineers-dedicated-docker-linux#8]
Hi
it looks like the serverdoesnt save the world, under appdata/space.engineers/config/world even though it says in the console. Is the world being saved elsewhere or do I have to set a different save location in the config? In the log it says the server is autosavin and also the /save command ingame worked, but I cant find the saved files and when I restart the server it goes back to an early version made when I hosted it from my PC. I'm not very experienced with this, hope you can help me.
[SpaceEngineersDedicated_20210221_160542644.log](https://github.com/mmmaxwwwell/space-engineers-dedicated-docker-linux/files/6018045/SpaceEngineersDedicated_20210221_160542644.log)

**Comment by mmmaxwwwell** [comment]
Take a look at the 2nd to last line in this excerpt from the log you sent me.
```
2021-02-21 16:07:03.581 - Thread:   1 ->  Executing /save command
2021-02-21 16:07:03.585 - Thread:   1 ->  Saving world - START
2021-02-21 16:07:03.585 - Thread:   1 ->     Making world state snapshot.
2021-02-21 16:07:03.586 - Thread:   1 ->     Before snapshot.: GC Memory: 504 B
2021-02-21 16:07:03.710 - Thread:   1 ->     After snapshot.: GC Memory: 502 B
2021-02-21 16:07:03.712 - Thread:   1 ->     Directory cleanup: GC Memory: 502 B
2021-02-21 16:07:03.712 - Thread:   1 ->  Saving world - END
2021-02-21 16:07:03.717 - Thread:   7 ->  Session snapshot save - START
2021-02-21 16:07:03.718 - Thread:   7 ->     Checking file access for files in target dir.
2021-02-21 16:07:03.719 - Thread:   7 ->     Couldn't access file 'Asteroid_-1_-1_0_10_153014550.vx2'.
2021-02-21 16:07:03.729 - Thread:   1 ->  Saving finished
```

I'm guessing the dedicated server hit a permissions error trying to write the files to disk and aborted.

This article gives a good intro to how permissions work in a unix system. I would take a half hour to read and really understand this article. You probably just need to chown and/or chmod the World/ folder and the files inside. https://medium.com/swlh/how-unix-file-permissions-work-accaf4cd60a2 

You aren't the only person bumping into this kind of issue. I'm working on a solution but may not be finished for a bit.

Could you run these three commands in the root of the repo, and paste the output here? 
```id```
```ls -ld ./appdata/space-engineers/config/World```
```ls -ld ./appdata/space-engineers/config/World/*```

If you want, you can pull down the permissions branch and see if that works. Its a work in progress, and has some disadvantages, but I'd appreciate it if you could tell me if it fixes your issue. Its going to take quite a bit longer to start the first time because it will be rebuilding the container from scratch on your computer, rather than pulling an image from dockerhub. It will also chown the files in the world folder for you, so switching to it, running it once, and returning to the master branch might fix your issue.
The disadvantages are: 
* first run will rebuild the container from scratch
* steamcmd updates are re-downloaded every time the server reboots
* slower gameserver boot

To switch to the permissions branch, from the root of the repo run: ```git fetch && git checkout permissions && git pull```
Then, run ```./start``` to start the server.
After the test, you can run ```git checkout master``` to return to the main branch.

**Comment by Allesstein** [comment]
Thank you for your reply. I fixed the issue yesterrday by adding the line `sudo chmod -R 777 appdata` after the first line in the start file in the root of the docker. This fixes the permission issues from the docker container.
As for the outputs of the three commands:
`id` returns:
`uid=1001(steam) gid=1001(steam) groups=1001(steam),27(sudo)`
`ls -ld ./appdata/space-engineers/config/World` returns:
`drwxrwxrwx 3 steam steam 4096 Feb 21 20:27 ./appdata/space-engineers/config/World`
`ls -ld ./appdata/space-engineers/config/World/*` returns:
`-rwxrwxrwx 1 steam      steam         3577 Feb 21 20:27 ./appdata/space-engineers/config/World/Asteroid_0_0_0_12_1353761627.vx2
-rwxrwxrwx 1 steam      steam        16494 Feb 21 20:27 ./appdata/space-engineers/config/World/Asteroid_0_0_-1_0_151977777.vx2
-rwxrwxrwx 1 steam      steam         5064 Feb 21 20:27 ./appdata/space-engineers/config/World/Asteroid_0_0_-1_10_275299322.vx2
-rwxrwxrwx 1 steam      steam         1974 Feb 21 20:27 ./appdata/space-engineers/config/World/Asteroid_0_0_-1_11_407358244.vx2
-rwxrwxrwx 1 steam      steam         3781 Feb 21 20:27 ./appdata/space-engineers/config/World/Asteroid_0_0_-1_1_1580584003.vx2
-rwxrwxrwx 1 steam      steam         2220 Feb 21 20:27 ./appdata/space-engineers/config/World/Asteroid_0_0_-1_13_1621682555.vx2
-rwxrwxrwx 1 steam      steam        19784 Feb 21 20:27 ./appdata/space-engineers/config/World/Asteroid_0_0_-1_2_2112022140.vx2
-rwxrwxrwx 1 steam      steam        26329 Feb 21 20:27 ./appdata/space-engineers/config/World/Asteroid_0_0_-1_26_1178575526.vx2
-rwxrwxrwx 1 steam      steam         6887 Feb 21 20:27 ./appdata/space-engineers/config/World/Asteroid_0_0_-1_7_1636415158.vx2
-rwxrwxrwx 1 steam      steam        35258 Feb 21 20:27 ./appdata/space-engineers/config/World/Asteroid_0_0_-1_8_1751400952.vx2
-rwxrwxrwx 1 steam      steam         3270 Feb 21 20:27 ./appdata/space-engineers/config/World/Asteroid_0_-1_0_1_66806555.vx2
-rwxrwxrwx 1 steam      steam        18267 Feb 21 20:27 ./appdata/space-engineers/config/World/Asteroid_-1_0_0_7_863598328.vx2
-rwxrwxrwx 1 steam      steam         3773 Feb 21 20:27 ./appdata/space-engineers/config/World/Asteroid_-1_-1_0_10_153014550.vx2
-rwxrwxrwx 1 steam      steam         4644 Feb 21 20:27 ./appdata/space-engineers/config/World/Asteroid_-1_-1_0_4_1486337851.vx2
-rwxrwxrwx 1 steam      steam         9505 Feb 21 20:27 ./appdata/space-engineers/config/World/Asteroid_-1_-1_0_9_229665640.vx2
drwxrwxrwx 7 allesstein allesstein    4096 Feb 21 20:27 ./appdata/space-engineers/config/World/Backup
-rwxrwxrwx 1 steam      steam       140565 Feb 21 20:27 ./appdata/space-engineers/config/World/RedShipCrashed-1.vx2
-rwxrwxrwx 1 steam      steam      3869200 Feb 21 20:27 ./appdata/space-engineers/config/World/SANDBOX_0_0_0_.sbs
-rwxrwxrwx 1 steam      steam       698428 Feb 21 20:27 ./appdata/space-engineers/config/World/SANDBOX_0_0_0_.sbsB5
-rwxrwxrwx 1 steam      steam         6451 Feb 21 20:27 ./appdata/space-engineers/config/World/Sandbox_config.sbc
-rwxrwxrwx 1 steam      steam       175610 Feb 21 20:27 ./appdata/space-engineers/config/World/Sandbox.sbc
-rwxrwxrwx 1 steam      steam        48881 Feb 20 12:09 ./appdata/space-engineers/config/World/thumb.jpg`

As for your WIP solution I'm not quite sure what you mean with 'chown the files'? Do I have to save the world and copy it back to the corresponding folders?
If you still want to me to try it, even after my fix, give me a heads up.

**Comment by mmmaxwwwell** [comment]
Nope, if you are up and running, don't worry about it.

Read that medium article, it says what chown is.

Keep in mind anyone can read/write those files on your PC, in practice 777ing a folder/files is usually a terrible idea.

Thanks for running those commands for me, I'm closing this.
